apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: newfeed
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Tranloi2k/New-Feed-MicroServices-config
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: newfeed
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m